### PR TITLE
fix(NcRichText): async import remark-gfm library

### LINKED ISSUE #6246: [Enhancement] NcRichText: `remark-gfm` could be async loaded to reduce initial size
rehype-highligh is now async loaded, which reduces the initial component size by ~110kB

image

Did a quick test, remark-gfm is 40kB and could be extracted as well. Shall we do it?

_Originally posted by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/issues/6212#issuecomment-2479118408_

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

- Fix #6246
- `remark-gfm` is 39.5 kB in dev build, which is 30% of rehype-highlight library size (111kB which we're also importing async)
- `rehype-highlight` won't be imported for code blocks without language provided/recognised
- ⚠️ if all conditions are met, that would cause two re-renders of the first component

### 🖼️ Screenshots

No visual changes

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade
Signed-off-by: Maksim Sukharev <antreesy.web@gmail.com>

### CODE REVIEW

File: src/components/NcRichText/NcRichText.vue [hunk 1]
```diff
@@ -410,6 +419,12 @@ export default {
 	},
 	emits: ['interact:todo'],
 
+	setup(props) {
+		if (props.useExtendedMarkdown && !remarkGfmLoaded.value) {
+			importRemarkGfmLibrary()
+		}
+	},
```
Comment (ShGKme) [inline src/components/NcRichText/NcRichText.vue:426]: This loads the lib only if `useExtendedMarkdown` was true initially. It doesn't support prop update.

File: src/components/NcRichText/NcRichText.vue [hunk 2]
```diff
@@ -489,9 +504,11 @@ export default {
...
 
 						if (!tag.startsWith('#')) {
-							if (this.useExtendedMarkdown) {
-								if (tag === 'code' && !rehypeHighlightLoaded.value) {
-									importRehypeLibrary()
+							if (this.useExtendedMarkdown && remarkGfmLoaded.value) {
+								if (tag === 'code'
+									&& attrs?.attrs?.class?.includes('language')
+									&& !rehypeHighlightLoaded.value) {
+									importRehypeHighlightLibrary()
```
Comment (ShGKme) [inline src/components/NcRichText/NcRichText.vue:511]: makes sense 👍

File: src/components/NcRichText/NcRichText.vue [hunk 3]
```diff
@@ -321,12 +320,22 @@ import { RouterLink } from 'vue-router'
...
+let remarkGfm
+const remarkGfmLoaded = ref(false)
+/**
+ * Load 'remark-gfm' library when prop `useExtendedMarkdown` is truthy
+ */
+async function importRemarkGfmLibrary() {
+	const module = await import('remark-gfm')
+	remarkGfm = module.default
+	remarkGfmLoaded.value = true
+}
```
Comment (ShGKme) [inline src/components/NcRichText/NcRichText.vue:332]: Just realized, we only need one variable here.

```suggestion
const remarkGfm = ref(null)
/**
 * Load 'remark-gfm' library when prop `useExtendedMarkdown` is truthy
 */
async function importRemarkGfmLibrary() {
	const module = await import('remark-gfm')
	remarkGfm.value = module.default
}
```

**Review by ShGKme — COMMENTED** [review]
I'm not sure this is a good idea with `remark-gfm`.

If the connection is slow - it first renders the raw text value, and then it flashes to rendered Markdown.

Unlike `code => code with highlights` update, this is a huge visible change. Imagine a message with headings and lists, that is first a plain text and then formatted.

I'm not sure we need a dynamic module here. But if we do it, we should render content ONLY when `remark-gfm` is loaded, and render nothing during loading.

**Review by juliusknorr — APPROVED** [review]
