### PR TITLE
fix(NcHeaderMenu): pause trap stack on opening

### LINKED ISSUE #5385: NcAppNavigation in mobile state blocks interacting with dialogs
When it's in `mobile` state, focus trap is attached to toggle, and thus any open dialog would be inaccessible from keyboard (not saying that I couldn't type in TextField)

image

ncdialog-focustrap

Any known PR, where this regression could come from?

_Originally posted by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/issues/5335#issuecomment-1985959176_

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

- Fix #5385
- Fix https://github.com/nextcloud/spreed/issues/13062

With `is-nav` prop NcHeaderMenu doesn't start a focus-trap and therefore doesn't pause existing ones. That prevents any click in mobile state, as focus returned to AppNavigation

Alternatives for NcAppNavigation:
- release focus-trap on click outside
- toggle component to closed state on click outside

### 🖼️ Screenshots

🏡 After (cherry-picked to stable8 + applied to server repo)

https://github.com/user-attachments/assets/b2e8cd28-edbb-4ea2-ad40-104c55cf86db

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 2️⃣ Backport to `stable8` for maintained Vue 2 version or not applicable

### CODE REVIEW

File: src/components/NcHeaderMenu/NcHeaderMenu.vue [hunk 1]
```diff
@@ -154,6 +155,12 @@ onClickOutside(headerMenu, () => setMenuState(false), { ignore })
 // Pressing escape should close the menu
 useHotKey('Escape', () => setMenuState(false), { prevent: true })
 
+// When component has its own custom focus management
+// The global focus trap stack should be paused
+useTrapStackControl(() => isOpened.value, {
```
Comment (ShGKme) [inline src/components/NcHeaderMenu/NcHeaderMenu.vue]:
```suggestion
useTrapStackControl(isOpened, {
```

**Review by susnux — APPROVED** [review]
