### PR TITLE
fix(NcRichContenteditable): fix pasted text handling

### LINKED ISSUE #4821: NcRichContenteditable not accepting clipboard pasted text
* type a text
* paste text from clipboard
=> the new text is not included in e.g. talk posts

* add a line brake after the pasted text
=> the new text is included

### PR DESCRIPTION
**Pull request by DorraJaouad**
### ☑️ Resolves

- Fix #4821

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
pasted-text | pasted-text-fixed

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

### CODE REVIEW

File: src/components/NcRichContenteditable/NcRichContenteditable.vue [hunk 1]
```diff
@@ -836,59 +832,6 @@ export default {
...
-		 * to properly be deleted on backspace, we have to hack 👀
-		 * https://stackoverflow.com/a/59383394/3885878
-		 * https://stackoverflow.com/a/30574622
-		 *
-		 * @param {Event} event the delete keydown event
-		 */
-		onDelete(event) {
-			if (!this.isFF || !window.getSelection) {
-				return
-			}
```
Comment (ShGKme) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:850]: If you remove this method, `isFF` is also not needed anymore.

File: src/components/NcRichContenteditable/NcRichContenteditable.vue [hunk 2]
```diff
@@ -820,7 +814,9 @@ export default {
 		 * @param {string} htmlOrText the html content (or raw text with @mentions)
 		 */
 		updateValue(htmlOrText) {
-			const text = this.parseContent(htmlOrText)
+			let text = this.parseContent(htmlOrText)
+			// Some browsers add a newline at the end of the contenteditable
+			text = text === '\n' ? '' : text
```
Comment (ShGKme) [inline src/components/NcRichContenteditable/NcRichContenteditable.vue:819]: The comment seems to not document the following line. Let's adjust to something like

```suggestion
			// Browsers keep <br> after erasing contenteditable
			text = text === '\n' ? '' : text
```

- Some browsers => browsers (it is not browser-specific. Or is it?)
- At the end => after erasing (not the ending but entire content is checked)

**Review by ShGKme — APPROVED** [review]

File: src/components/NcRichContenteditable/NcRichContenteditable.vue (hunk 1 above)
Comment (Antreesy) [reply src/components/NcRichContenteditable/NcRichContenteditable.vue:850]: Unrelated to pasting issue, but noticed:
if input is started or ended with embedded HTML (mention) `"@Test01 anyword @Test01"`:
- 🐞 in FF cursor isn't moving to the very start or end with ⬅️ ➡️ keys (⬆️ ⬇️ are working)
- 🐞 in Safari cursor jumps to the very beginning
- ✅ in Chrome everything is fine

**Comment by SystemKeeper** [comment]
image

Output raw still has a `\n` at the end? 🤔

**Comment by DorraJaouad** [comment]
> Output raw still has a \n at the end? 🤔

We don't remove it when there is text because browser will add it anyway, we remove when it's the only text (browser leftover)

**Comment by ShGKme** [comment]
> Output raw still has a `\n` at the end? 🤔

It doesn't hurt (unlike then it contains only `<br>`)

**Review by Antreesy — APPROVED** [review]
Tested in Chrome, Firefox, Safari
