### PR TITLE
fix(NcNoteCard): too large icon padding

### LINKED ISSUE #7117: [9.0.0-rc.3] NcNoteCard looks different than in v8
In context chat when updating to v9 the NcNoteCard changes from this:
Image
to this:
Image

Relevant pr: https://github.com/nextcloud/context_chat/pull/136

### PR DESCRIPTION
**Pull request by raimund-schluessler**
### ☑️ Resolves

- Fix #7117

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
grafik | grafik

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable
- [x] 2️⃣ Backport to `stable8` for maintained Vue 2 version or not applicable

### CODE REVIEW

File: src/components/NcNoteCard/NcNoteCard.vue [hunk 1]
```diff
@@ -161,6 +161,8 @@ const iconPath = computed(() => {
 
 	&__icon {
 		color: var(--note-theme);
+		min-height: var(--note-card-icon-size);
+		min-width: var(--note-card-icon-size);
```
Comment (ShGKme) [inline src/components/NcNoteCard/NcNoteCard.vue]: The difference from the v8 is the icon component, styles are the same.
- Ref: https://github.com/nextcloud-libraries/nextcloud-vue/pull/6985/files

`inline` prop should work. If it doesn't, let's add a prop to remove min size.

**Review by ShGKme — CHANGES_REQUESTED** [review]

File: src/components/NcNoteCard/NcNoteCard.vue (hunk 1 above)
Comment (raimund-schluessler) [reply src/components/NcNoteCard/NcNoteCard.vue]: Inline prop seems to work fine.

**Comment by raimund-schluessler** [comment]
Inline prop works. Please set my DCO to pass, I only have my mobile at hand right now.

**Comment by ShGKme** [comment]
Squashed into a single commit

**Review by ShGKme — APPROVED** [review]
