### PR TITLE
fix(NcActions): NcActionCheckbox and NcActionRadio icon alignment

### LINKED ISSUE #5957: NcActionRadio does not align with NcActionButton, NcActionCheckbox, etc
image

### PR DESCRIPTION
**Pull request by GretaD**
### ☑️ Resolves

- Fix #5957

### 🖼️ Screenshots

🏚️ Before | 🏡 After
Screenshot from 2024-08-14 10-42-45
|
Screenshot from 2024-08-14 11-36-43

### 🚧 Tasks

- [x] Change the margin of both ncactioncheckbox and ncactionradio so they align. I decreased the margin because they dont fit with the other elements, like 'remove attendee' in the screenshot. I think that comes from making icons smaller.
### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable
- [x] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

### CODE REVIEW

**Review by susnux — APPROVED** [review]

File: src/components/NcActionCheckbox/NcActionCheckbox.vue [hunk 1]
```diff
@@ -206,8 +206,7 @@ export default {
 
 		&::before {
 			margin-block: 0 !important;
-			// 16px is the width of the checkbox including the border
-			margin-inline: calc((var(--default-clickable-area) - 16px) / 2) !important;
+			margin-inline: calc((var(--default-clickable-area) - 14px) / 2) !important;
```
Comment (ShGKme) [inline src/components/NcActionCheckbox/NcActionCheckbox.vue:209]: Probably, we should either add CSS variable for it, or change layout here to not use this number to avoid magic numbers.

P.S. On all supported versions on server it is 14px, not 16px

https://github.com/nextcloud/server/blob/stable28/core/css/inputs.scss#L414

**Review by ShGKme — APPROVED** [review]
