### PR TITLE
fix(NcAppSidebarTabs): override checkbox radio switch only in navigation

### LINKED ISSUE #4822: `NcCheckboxRadioSwitch` styles are overridden inside `NcAppSidebarTab`
`:deep` selector in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4815 is used to override `NcCheckboxRadioSwitch` styles in the tab list.

But due to `deep`, it overrides all `NcCheckboxRadioSwitch` on the tab, including content:

image

### PR DESCRIPTION
**Pull request by ShGKme**
### ☑️ Resolves

* Fix #4822

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
image | image

### 🚧 Tasks

- [x] Override with `:deep` `NcCheckboxRadioSwitch` styles only inside tabslist navigation, not inside all the tab, including tab content

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable

### CODE REVIEW

**Review by JuliaKirschenheuter — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]

**Review by jancborchardt — COMMENTED** [review]
Thanks!

File: src/components/NcAppSidebar/NcAppSidebarTabs.vue [hunk 1]
```diff
@@ -271,6 +271,26 @@ export default {
...
+				border-radius: var(--default-grid-baseline) var(--default-grid-baseline) 0 0 !important;
+				margin: 0 !important;
+				border-bottom: var(--default-grid-baseline) solid transparent !important;
+				.checkbox-content__icon--checked > * {
+					color: var(--color-main-text) !important;
+				}
+			}
+			&.checkbox-radio-switch--checked .checkbox-radio-switch__content{
+				background: transparent !important;
+				color: var(--color-main-text) !important;
```
Comment (szaimen) [inline src/components/NcAppSidebar/NcAppSidebarTabs.vue:290]: The correct text color in that case would have been `--color-primary-element-text`

File: src/components/NcAppSidebar/NcAppSidebarTabs.vue [hunk 2]
```diff
@@ -271,6 +271,26 @@ export default {
...
+		& :deep(.checkbox-radio-switch--button-variant) {
+			border: unset !important;
+			border-radius: 0 !important;
+			.checkbox-content {
+				padding: var(--default-grid-baseline);
+				border-radius: var(--default-grid-baseline) var(--default-grid-baseline) 0 0 !important;
+				margin: 0 !important;
+				border-bottom: var(--default-grid-baseline) solid transparent !important;
+				.checkbox-content__icon--checked > * {
+					color: var(--color-main-text) !important;
```
Comment (szaimen) [inline src/components/NcAppSidebar/NcAppSidebarTabs.vue:285]: probably same here

File: src/components/NcAppSidebar/NcAppSidebarTabs.vue (hunk 1 above)
Comment (susnux) [reply src/components/NcAppSidebar/NcAppSidebarTabs.vue:290]: would you mind creating a PR for this? :pray:

Comment (szaimen) [reply src/components/NcAppSidebar/NcAppSidebarTabs.vue:290]: done in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4834
